services:
  - type: web
    name: syncdraw-backend-baq7
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ALLOWED_ORIGIN
        value: https://sync-draw-eight.vercel.app
      - key: PORT
        value: 8080