services:
  - type: web
    name: syncdraw-backend-baq7
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: ALLOWED_ORIGIN
        value: https://sync-draw-eight.vercel.app
      - key: PORT
        value: 8080