services:
  - type: web
    name: syncdraw-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://sync-draw-eight.vercel.app,http://localhost:3000,http://localhost:5173
      - key: PORT
        value: 8080
